# Generated by Django 3.2.16 on 2022-11-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItems',
            fields=[
                ('type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('mash', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'additional_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('remain', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount_of_coffee', models.IntegerField(null=True)),
                ('amount_of_milk', models.IntegerField(null=True)),
                ('amount_of_chocolate', models.IntegerField(null=True)),
                ('amount_of_syrub', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('order_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('received', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_stock', models.DateField(null=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('sweet_level', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'sweet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=10)),
                ('point', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
